Pocketeers/pp-ptf

README.md
readme has been updated. pull requested.
=> Readme edit - first lines

README.md
=> readme diubah

app/form.html, app/userform.php
=> add  2 form

app/ptf.sql
=> edited ptf.sql file

app/updatepost.php
=> change file name

app/addpost.php, app/create-post.php, app/deletepost.php, app/updatepost.php
=> change index directory

app/deletepost.php, app/delmessage.php, app/index.php, app/main.css, app/updatepost.php, app/viewpost.php
=> edit files

app/login.php, app/loginsuccess.php, app/logout.php
=> dapat betulkan file login

app/addpost.php, app/create-post.php, app/deletepost.php, app/delmessage.php, app/loginsuccess.php, app/updatepost.php, app/viewpost.php
=> Tambah comment

app/addregister.php, app/login.php, app/prereg.php
dah dapat elak daripada conflict
=> betulkan file login.php

app/addpost.php, app/index1.php, app/viewpost1.php
=> tambah file index1, viewpost1 & edit 2 file

app/addpost.php, app/create-post.php, app/deletepost.php, app/delmessage.php, app/index.php, app/index1.php, app/updatepost.php, app/viewpost.php, app/viewpost1.php
edit 9 file & fix link directory
=> edit 9 file

app/ptf.sql
=> update sql file

app/deletepost.php, app/delmessage.php, app/index.php, app/index1.php, app/main.css, app/resetid.php, app/updatepost.php, app/viewpost.php, app/viewpost1.php
id table dah update & file php dah edit
=> edit 8 file & 1 file baru

app/index.php, app/index1.php, app/prereg.php, app/register.php
=> change table column & add access control to register.php

app/logout.php, app/prereg.php, app/ptf.sql, app/register.php
fix register file & update database backup
=> fix register file & update database backup

app/form.html
=> fix translation

app/deletepost.php, app/delmessage.php, app/form.html, app/formpreview.php, app/getdelmessage.php, app/getindex.php, app/getindex1.php, app/getupdatepost.php, app/getviewpost.php, app/getviewpost1.php, app/index.php, app/index1.php, app/send.php, app/updatepost.php, app/viewpost.php, app/viewpost1.php
=> add external php file

app/addmsg.php, app/addpost.php, app/create-post.php, app/form.php, app/getform.php, app/getindex.php, app/getuserlogin.php, app/send.php, app/sent.php, app/userlogin.php
=> add external files

app/getindex.php
=> edit index.php

app/form.php, app/getform.php, app/phpinfo.php, app/send.php
=> edit form files

app/getform.php, app/getindex.php, app/send.php
=> edit 3 files

app/form.php, app/getindex.php, app/index.php, app/index1.php
=> edit index & form

app/index.php, app/prereg.php, app/register.php
=> new update
